version: "3.7"
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "9010:9010"
    volumes:
      - .:/backend
  app:
    container_name: app
    restart: always
    build: ./frontend
    ports:
      - "9011:9011"
    volumes:
      - .:/frontend
    links:
      - backend