version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/mongo/data/db
    ports:
      - "27017:27017"
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - .:/backend
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  app:
    container_name: app
    restart: always
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/frontend
    links:
      - backend